Update the SAP Loggregator documentation
SAP-docs/btp-cloud-platform pull request #119
Opened 2022-11-24 14:19 UTC by ZPascal

Hi colleagues, we (CF-Core/ Team Loggregator & CF-Persistence) want to add more documentation about the syslog drain functionality and the corresponding app log limitations.

2022-11-25 10:32 UTC, sdanter commented
@ZPascal which is the intended takt/release for this?

2022-11-25 11:37 UTC, ZPascal commented
Hi @sdanter, it would be good to ship it with 12a.

2022-11-28 15:11 UTC, ZPascal commented on docs/10-concepts/cloud-foundry-environment-9c7092c.md
Good idea. I've updated the documentation and restructured the documentation. @stefanlay Could you please take a look?

2022-12-07 16:10 UTC, stefanlay requested changes

2022-12-07 16:10 UTC, stefanlay commented on docs/10-concepts/cloud-foundry-environment-9c7092c.md
> +-   In the Cloud Foundry environment, there’s a logging rate limit to guard against malicious applications. The limit is in the range of up to a few thousand logs per second per application instance.
I would prefer to have an extra sentence about it because the first topic is related to the log production and the new one to the consumption of logs.
To be more precise, I propose to phrase it like "Applications requiring sent envelopes to be delivered to external Log Management Services should use the CloudFoundry syslog drain capability."

2022-12-08 09:42 UTC, sdanter commented
Hello @stefanlay and @ZPascal , is the discussion around this finished and are the documentation changes finalized? I will add them to the documentation once it's confirmed.

2022-12-08 12:58 UTC, ZPascal commented on docs/10-concepts/cloud-foundry-environment-9c7092c.md
> +-   In the Cloud Foundry environment, there’s a logging rate limit to guard against malicious applications. The limit is in the range of up to a few thousand logs per second per application instance.
I've changed the structure.

2022-12-08 14:01 UTC, stefanlay approved these changes

2022-12-09 13:34 UTC, ZPascal commented
@sdanter We've finished the discussion. Feel free to ship/ merge it.

2022-12-09 19:20 UTC, sdanter requested changes
> should use the CloudFoundry syslog drain capability

Missing whitespace, should be Cloud Foundry.

2022-12-09 19:21 UTC, sdanter commented
Changes were added and should be released with 12a. Noticed a missing whitespace in the new part for BTP-specific configurations though.

2022-12-13 15:24 UTC, DavidMitreski5 commented
Hello @sdanter, should we close this pull request if all the changes are made?

2022-12-13 15:30 UTC, sdanter commented
> Hello @sdanter, should we close this pull request if all the changes are made?

Yes we can close it

2022-12-13 16:06 UTC, closed without merging

2022-12-13 19:40 UTC, ZPascal commented
Thx @sdanter for the support.