Add documentation on CF API concurrency rate limit
SAP-docs/btp-cloud-platform pull request #72
Opened 2022-05-30 11:32 UTC by FloThinksPi

2022-05-30 11:40 UTC, FloThinksPi commented
CLA Seems to be broken ? 
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/5863788/170984882-320fd0a8-d820-4c38-a684-1cda6e75b77a.png">

2022-06-02 11:23 UTC, je-hal commented
@FloThinksPi : It seems if you wait a little longer, signing the CLA should work, see cla-assistant/cla-assistant#874. Could you please try again?

2022-06-17 11:50 UTC, sdanter requested changes
Some small suggestions to maintain consistency regarding external links.

2022-06-17 11:50 UTC, sdanter commented on docs/10-concepts/cloud-foundry-environment-9c7092c.md
> +-   In addition to the general rate limit on the Cloud Foundry API, requests for certain API endpoints related to services face a separate limit on concurrent requests (see details [here](https://doc
```suggestion
-   In addition to the general rate limit on the Cloud Foundry API, requests for certain API endpoints related to services face a separate limit on concurrent requests. The Cloud Foundry API responds with HTTP status code `429` if a rate limit is reached and provides a Retry-After header suggesting when the client can attempt a retry. For more information, see https://docs.cloudfoundry.org/running/rate-limit-cloud-controller-api.html#Rate%20Limit%20Responses:%20Service%20Brokers .
```

2022-06-20 14:58 UTC, sdanter commented
Thank you for your contribution @FloThinksPi, the documentation will be updated with the next release.

2022-06-20 14:58 UTC, closed without merging